import {
  PortfolioLogo,
  Map,
  Messenger,
  Taskify,
  Social,
  Spotify,
  TikTok,
  Rasooi,
  Portfolio,
} from "../Assets/AssetsList";

export const ProjectList = [
  {
    name: "Namaste Yatra",
    image: Map,
    skills: ["JS, NodeJS, ExpressJS, MongoDB, Cloudnary, MapBox, Render, BootStrap"],
    codeLink: "https://github.com/Shashi-Srivastav/Namaste-Yatra",
    demoLink: "https://namaste-yatra.vercel.app/listings",
    info: "Namaste Yatra is a tech-driven travel platform leveraging a powerful stack to redefine user experiences. With JavaScript and Node.js at its core, the platform ensures real-time responsiveness. Express.js structures its architecture, while Bootstrap crafts a visually captivating front-end. MongoDB and Mongoose provide a flexible data layer, with MongoDB Atlas extending to the cloud. Passport ensures secure user authentication, and Joi enforces data integrity. Mapbox introduces spatial exploration, and Cloudinary optimizes image management. The platform's tech ensemble creates a dynamic and responsive environment, setting new standards in travel platforms.",
    MERN:"true",
  },
  {
    name: "Rasooi Ghar",
    image: Rasooi,
    skills: ["ReactJs, Redux, Swiggy API, Tailwind, Vercel"],
    codeLink: "https://github.com/Shashi-Srivastav/Rasooi-Ghar-Restaurant",
    demoLink: "https://rasooi-ghar-restaurant.vercel.app/",
    info: "Developed a Swiggy clone named 'Rasooi Ghar' with features like item addition via a card system, efficient state management, form handling, and dynamic routing. This project demonstrates my in-depth knowledge of React hooks, custom hooks, modern bundling techniques, high-order components, dev tools, suspense components, React lifecycle, function-based components, class-based components, Jest, React Testing Library, unit test principles, and React-Redux actions and reducers.",
    mern:"true",
  },
  {
    name: "TikTok Clone",
    image: TikTok,
    skills: ["Next JS, React, Typescript, Tailwind CSS, Zustand, AppWrite, Vercel"],
    codeLink: "https://github.com/Shashi-Srivastav/TikTok-Clone",
    demoLink: "https://tiktok-dev-clone.vercel.app/",
    info: "I've successfully crafted a TikTok clone using cutting-edge technologies, including Next.js and React for the frontend, Typescript for enhanced code reliability, Tailwind CSS for a sleek and responsive design, Zustand for state management, and AppWrite for backend services. This project brings the excitement of short-form videos to life, combining the efficiency of Next.js, the clarity of Typescript, and the seamless deployment on Vercel for a smooth user experience.",
    mern:"true",
  },
  {
    name: "Personal Portfolio 2.0",
    image: Portfolio,
    skills: ["ReactJs, Jest, EmailJS, Framer Motion"],
    codeLink: "https://github.com/Shashi-Srivastav/Portfolio2.0",
    demoLink: "https://shashi-srivastava.vercel.app/",
    info: "Developed a personal portfolio website using a modern tech stack to showcase projects and skills. This project integrates various libraries and tools to enhance functionality and user experience. The portfolio includes features such as animated components using Framer Motion, an interactive GitHub activity calendar, smooth scrolling effects, a dark mode toggle, and a vertical timeline component to display career milestones. Form handling is implemented with EmailJS for contact forms, and comprehensive testing is conducted using Jest and React Testing Library. The website is built with React and React Router for efficient navigation and is optimized for performance using Web Vitals.",
    mern:"true",
  },
  {
    name: "Personal Portfolio",
    image: PortfolioLogo,
    skills: ["TailWind, NextJS, EmailJS, BootStrap,Framer Motion"],
    codeLink: "",
    demoLink: "https://shashi-srivastava-portfolio.vercel.app/",
    info: "In my latest project, the Personal Portfolio developed with NextJS, I've curated a visually appealing and responsive interface. Employing Tailwind CSS for polished styling, Bootstrap icons for enhanced visuals, and Framer Motion for dynamic animations, the portfolio provides a modern and engaging user experience. For seamless communication, I've integrated Emailjs and MainJS, enabling direct email submissions from the portfolio. Explore the portfolio to discover the seamless blend of design and functionality.",
    js:"true",
  },
  // {
  //   name: "Taskify",
  //   image: Taskify,
  //   skills: ["Next.js 13, React, Convex, Tailwind"],
  //   codeLink: "https://github.com/Shashi-Srivastav/Taskify",
  //   demoLink: "https://taskify-your-work.vercel.app/",
  //   info: "I've successfully developed a Notion clone using the latest technologies, including Next.js 13 for the frontend, React for building dynamic user interfaces, Convex for state management, and Tailwind CSS for a sleek and responsive design. This project replicates the core functionalities of Notion, providing a powerful and user-friendly experience.",
  // },
  // {
  //   name: "Messenger Clone",
  //   image: Messenger,
  //   skills: ["Next.js 13, React, Tailwind, Prisma, MongoDB, NextAuth, Pusher"],
  //   codeLink: "https://github.com/Shashi-Srivastav/Messenger",
  //   demoLink: "https://dev-messenger.vercel.app/",
  //   info: "I've crafted an impressive messenger clone using cutting-edge technologies. Leveraging Next.js 13 for a fast and seamless frontend, React for dynamic UI components, and Tailwind CSS for a polished design. The backend is powered by Prisma and MongoDB, ensuring efficient data management. Authentication is handled seamlessly with NextAuth, and real-time updates are facilitated through Pusher. This project delivers a feature-rich and responsive messaging platform, offering a robust user experience.",
  // },
  // {
  //   name: "Snapgram",
  //   image: Social,
  //   skills: ["React JS, Appwrite, Tailwind CSS, React Query"],
  //   codeLink: "https://github.com/Shashi-Srivastav/Social-App",
  //   demoLink: "https://snapgram-dev.vercel.app/",
  //   info: "I've developed a dynamic social app using React JS, integrating Appwrite for backend services, Tailwind CSS for a modern and responsive design, and React Query for efficient data fetching and management. Users can seamlessly post content, follow others, and bookmark posts, creating an engaging and interactive social experience. This project combines the power of React ecosystem and Appwrite's capabilities to provide a feature-rich platform for social interactions.",
  // },
  {
    name: "Sportify Clone",
    image: Spotify,
    skills: ["HTML, CSS, JS"],
    codeLink: "https://github.com/Shashi-Srivastav/Project-Melodify-a-Spotify-Clone-App",
    demoLink: "https://shashi-srivastav.github.io/Project-Melodify-a-Spotify-Clone-App/",
    info: "The Sportify Clone, crafted with HTML, CSS, and JavaScript, prioritizes dynamic user experiences through focused DOM events. The project's responsive interface mirrors a music streaming platform, showcasing meticulous design and seamless interactivity. JavaScript takes the lead in ensuring real-time updates and engaging user interactions, making the Sportify Clone a captivating showcase of technical proficiency and user-centric design.",
    js:"true",
  },
];
